# Generated by Django 2.2.5 on 2019-10-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Placed_student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('EmailID', models.EmailField(max_length=254)),
                ('MobileNumber', models.CharField(max_length=100)),
                ('Fagg_percentage', models.FloatField(max_length=100)),
                ('F_YroPassing', models.CharField(max_length=100)),
                ('Sagg_percentage', models.FloatField(max_length=100)),
                ('S_YroPassing', models.CharField(max_length=100)),
                ('Tagg_percentage', models.FloatField(max_length=100)),
                ('T_YroPassing', models.CharField(max_length=100)),
                ('Total', models.FloatField(max_length=100)),
            ],
            options={
                'db_table': 'place_student',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('EmailID', models.EmailField(max_length=254)),
                ('MobileNumber', models.CharField(max_length=100)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=128)),
                ('Address', models.TextField()),
                ('City', models.CharField(max_length=70)),
                ('State', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=100)),
                ('ClassX_Board', models.CharField(max_length=100)),
                ('ClassX_Percentage', models.FloatField(max_length=100)),
                ('ClassX_YrOfPassing', models.CharField(max_length=100)),
                ('ClassXII_Board', models.CharField(max_length=100)),
                ('ClassXII_Percentage', models.FloatField(max_length=100)),
                ('ClassXII_YrOfPassing', models.CharField(max_length=100)),
                ('Fagg_percentage', models.FloatField(max_length=100)),
                ('F_YroPassing', models.CharField(max_length=100)),
                ('Sagg_percentage', models.FloatField(max_length=100)),
                ('S_YroPassing', models.CharField(max_length=100)),
                ('Tagg_percentage', models.FloatField(max_length=100)),
                ('T_YroPassing', models.CharField(max_length=100)),
                ('Total', models.FloatField(max_length=100)),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
